### ISSUE TITLE
FPS Problem

### ISSUE THREAD

**Issue by iartr** [avaneeshkumarmaurya/Barcode-Reader#11]
Why do you use hardcorded fps value as 1.0? It makes optimization problem.

> CameraSource.Builder builder = new CameraSource.Builder(getActivity(), barcodeDetector)
                .setFacing(CameraSource.CAMERA_FACING_BACK)
                .setRequestedPreviewSize(1600, 1024)
                .setRequestedFps(1.0f);

**Comment by ntnbrtnkv** [comment]
Did you test changes? Does it really improves performance?
https://github.com/avaneeshkumarmaurya/Barcode-Reader/commit/9fb6475e9d383904bccb4fe0a4c16b7a11509e63
Seems like it without fps lock app should lag

**Comment by iartr** [comment]
@ntnbrtnkv 
Yes, I did. With setRequestedFps(1.0f) your camera move veryyy slowly. There is no if line with limit fps is absent. And I have not found recommendations for limiting fps.
