### ISSUE TITLE
Barcode scanner not working in Android 6.0.1 and Android 5.0 on LG tablets

### ISSUE THREAD

**Issue by shehabattia96** [avaneeshkumarmaurya/Barcode-Reader#3]
Scanner not setting listener on those two Android versions. Updated the 6.0.1 to a 7.0 and the barcode scanner started working. Using the demo app.
Here's the logcat:
`
W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1702
I/DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 1702
W/DynamiteModule: Dynamite loader version < 2, falling back to loadModule2
I/Vision: Loading library libbarhopper.so
I/Vision: libbarhopper.so library load status: false
W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.`

**Comment by shehabattia96** [comment]
Worked on Android 5.0 after updating Google Play Services from 12.xx to 14.7.99.
Updated by following these directions (https://github.com/firebase/quickstart-android/issues/517#issuecomment-393290542):
Access the Google Settings screen:
a) Android <= L: App Drawer > Google Settings
b) Android >= M: Settings > Google
From Google Settings, go to the overflow menu → Help & feedback → overflow menu → View in Google Play Store.
If you see an [UPDATE] button, click it.

**Comment by zeroDivider** [comment]
but is it a good solution in production? you cannot count on users to remember that update google service.. :/
